### ISSUE TITLE
No update of Objects or Summary when Routines are started

### ISSUE THREAD

**Issue by FillyderErste** [Apollon77/ioBroker.alexa2#1066] opened 2023-09-17 15:04 UTC
Hi everyone,

I face trouble with the alexa adapter since several weeks. As mentione in the subject, the adapter (2 instances installed) does not update any object when a routine is started on any Echo Dot. 
Each instance shows green light in the instance overview, also the debug-log shows no error (screenshot below).

**Check if the Bug maybe is with Amazon**  
App is working. Routines can be started in the APP and Echo Dots confirm with "OK".

**Describe the bug**  
No update of any object (routine or summary for example) when triggering a routine on any Echo Dot, like described here #1052.
History-objects are updated, Routines-objects not, when triggering a routine in the Alexa App (I do not know if this is standard or not, never checked that before)
All Echo Dots are online acc. to the "online" objects.
![grafik](https://github.com/Apollon77/ioBroker.alexa2/assets/104793346/d7b6f953-1ff7-44e1-a23a-e9b69804aeba)

Triggering a command using the buttons in the object tree is possible, so that the corresponding Echo Dot runs the command.
![grafik](https://github.com/Apollon77/ioBroker.alexa2/assets/104793346/3ec05b3a-41e8-4fb3-8c1d-421559f48a76)

**To Reproduce**  
1. Restarted the instance - no change
2. Restarted docker container - no change
3. Installed a new instance - no change

**Expected behavior**  
Instance recognizes the command/routine from Echo Dots and updates the objects accordingly.

**Screenshots & Logfiles**  
Debug-Log
![grafik](https://github.com/Apollon77/ioBroker.alexa2/assets/104793346/15c6e5e3-7dd7-4e4a-a03f-84347ac215fa)

Instance running
![grafik](https://github.com/Apollon77/ioBroker.alexa2/assets/104793346/d0d15f7e-bcf6-470f-96e8-ddd7d1196b03)

**Versions:**  
 - Adapter version: 3.24.1
 - JS-Controller version: 4.0.24
 - Node version: 18.15.0
 - Operating system: Synology DSM 7.2 / Docker Image Buanet 8.0.0

**Additional context**  
n/a

**Comment by Apollon77** [comment] 2023-09-17 15:32
3.25.x is your friend ...
duplicate of the pinned #1045

**Closed by Apollon77** 2023-09-17 15:32 UTC
