### ISSUE TITLE
Alexa2.0 Commands are not working anymore.

### ISSUE THREAD

**Issue by polocup100** [Apollon77/ioBroker.alexa2#582] opened 2020-12-01 22:11 UTC
Since a few weeks the speak command is not working, the other commands also not work.

I tryed V3.3.1 and  3.2.4.
I get no error in the Logfile.

Any known Problems?
History is working fine.

Admin 4.0.10

alexa2.0 | 2020-12-01 23:02:58.675 | info | (10494) Alexa-Push-Connection established. Disable Polling
-- | -- | -- | --
alexa2.0 | 2020-12-01 23:02:56.833 | info | (10494) Subscribing to states...
alexa2.0 | 2020-12-01 23:02:42.962 | info | (10494) Alexa-Push-Connection disconnected - retry: Retry Connection in 15s
alexa2.0 | 2020-12-01 23:02:42.960 | info | (10494) Alexa-Push-Connection disconnected - retry: Retry Connection in 10s
alexa2.0 | 2020-12-01 23:02:42.958 | info | (10494) Alexa-Push-Connection Error: Error: WebSocket was closed before the connection was established
alexa2.0 | 2020-12-01 23:02:13.931 | info | (10494)     Device-type:A1ZB65LA390I4K  (VOLUME_SETTING,REMINDERS,TIMERS_AND_ALARMS,ASCENDING_ALARM_VOLUME,PERSISTENT_CONNECTION,DIALOG_INTERFACE_VERSION,CUSTOM_ALARM_TONE,SUPPORTS_SOFTWARE_VERSION,SO
alexa2.0 | 2020-12-01 23:02:13.930 | info | (10494) Report to developer as GitHub issue with details for device.  Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-01 23:02:13.929 | info | (10494) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-01 23:02:13.801 | info | (10494)     Device-type:A9YU3XB1OZ676  (DEEZER,VOLUME_SETTING,CHANGE_NAME,DEREGISTER_DEVICE,AMAZON_MUSIC,REMINDERS,TIMERS_AND_ALARMS,SIRIUSXM,PERSISTENT_CONNECTION,TIDAL,KINDLE_BOOKS,SUPPORTS_CONNECTE
alexa2.0 | 2020-12-01 23:02:13.800 | info | (10494) Report to developer as GitHub issue with details for device.  Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-01 23:02:13.799 | info | (10494) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-01 23:02:08.441 | info | (10494) starting. Version 3.2.4 in /opt/iobroker/node_modules/iobroker.alexa2, node: v12.18.3, js-controller: 3.1.6

Best regards 

Sascha

**Comment by Apollon77** [comment] 2020-12-01 22:27
No problems are know at the moment. Please try to setup a routine in the alexa app. Is speak working there? if not ... this is your reason

**Comment by polocup100** [comment] 2020-12-01 22:35
With a routine it is working.

Ingo Fischer <notifications@github.com> schrieb am Di., 1. Dez. 2020, 23:27:

**Comment by Apollon77** [comment] 2020-12-01 23:05
Please set adapter to debug log (Instances - export mode - column loglevel) and provide debug log of such a speak command

**Comment by Apollon77** [comment] 2020-12-01 23:06
Also: is announcement or any other command working?

**Comment by polocup100** [comment] 2020-12-02 06:48
Here is the Log:

alexa2.0 2020-12-02 07:44:54.008 debug (31522) Alexa-Remote: Sending
Request with {"host":"alexa.amazon.de","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}}
and data={"behaviorId":"PREVIEW","sequenceJson":"{\"
alexa2.0 2020-12-02 07:44:54.007 debug (31522) Alexa-Remote: No
authentication check needed (time elapsed 243581)
alexa2.0 2020-12-02 07:44:54.005 debug (31522) State changed
alexa2.0.Echo-Devices.G090LF1174550NK6.Commands.speak:
{"val":"Test","ack":false,"ts":1606891494001,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1606891

other Commands are also not working, like good morning...

Am Mi., 2. Dez. 2020 um 00:07 Uhr schrieb Ingo Fischer <
notifications@github.com>:

**Comment by Apollon77** [comment] 2020-12-02 07:50
For me everything is working. What are this for devices?

Please provide the log again but from the logfile on disk and not from admin (admin cut lines!)

And best save a manual "speak" routine and send the log from a direct speak and from activating that routine from within the adapter (restart adapter after you saved the routine)

**Comment by polocup100** [comment] 2020-12-02 17:08
Devices Echo Dot2,3 or show10".

2020-12-02 17:22:01.095  -  [34mdebug [39m: alexa2.0 (10887) State
changed alexa2.0.Echo-Devices.G090LF1174550QB7.Commands.speak:
{"val":"Flurtür 2OG
schließen","ack":false,"ts":1606926121089,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1606924653750}
2020-12-02 17:22:01.098  -  [34mdebug [39m: alexa2.0 (10887)
Alexa-Remote: No authentication check needed (time elapsed 337288)
2020-12-02 17:22:01.098  -  [34mdebug [39m: alexa2.0 (10887)
Alexa-Remote: Sending Request with
{"host":"alexa.amazon.de","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}}
and data={"behaviorId":"PREVIEW","sequenceJson":"{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"@type\":\"com.amazon.alexa.behaviors.model.SerialNode\",\"name\":null,\"nodesToExecute\":[{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"operationPayload\":{\"deviceType\":\"A3S5BH2HU6VAYF\",\"deviceSerialNumber\":\"G090LF1174550QB7\",\"locale\":\"de-DE\",\"customerId\":\"ASKC63P3YLN5L\",\"value\":4},\"type\":\"Alexa.DeviceControls.Volume\"},{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"operationPayload\":{\"deviceType\":\"A3S5BH2HU6VAYF\",\"deviceSerialNumber\":\"G090LF1174550QB7\",\"locale\":\"de-DE\",\"customerId\":\"ASKC63P3YLN5L\",\"textToSpeak\":\"Flurtür
2OG schließen\"},\"type\":\"Alexa.Speak\"},{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"operationPayload\":{\"deviceType\":\"A3S5BH2HU6VAYF\",\"deviceSerialNumber\":\"G090LF1174550QB7\",\"locale\":\"de-DE\",\"customerId\":\"ASKC63P3YLN5L\",\"value\":50},\"type\":\"Alexa.DeviceControls.Volume\"}]}}","status":"ENABLED"}

what do you mean with a manual "speak" routine ...

Am Mi., 2. Dez. 2020 um 08:50 Uhr schrieb Ingo Fischer <
notifications@github.com>:

**Comment by Apollon77** [comment] 2020-12-03 07:30
> what do you mean with a manual "speak" routine ...

Create a routine in alexa app that uses Speak (aslexa says something) with a custom text. the restart adapter and start this routine from the adapter

**Comment by lordnaicon** [comment] 2020-12-03 12:00
Hi habe auch das problem das Speak und Announcement nicht mehr funktionieren. Synology 218+ Docker 
habe den adapter und routinen schon neuinstalliert ... leider ohne erfolg.

`

2020-12-03 12:57:53.056  - info: host.buanet-iobroker stopInstance system.adapter.alexa2.0 (force=false, process=true)
--
2020-12-03 12:57:53.063  - info: host.buanet-iobroker stopInstance system.adapter.alexa2.0 send kill signal
2020-12-03 12:57:53.068  - info: alexa2.0 (27633) Got terminate signal TERMINATE_YOURSELF
2020-12-03 12:57:53.073  - info: alexa2.0 (27633) terminating
2020-12-03 12:57:53.076  - info: alexa2.0 (27633) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2020-12-03 12:57:53.601  - info: host.buanet-iobroker instance system.adapter.alexa2.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2020-12-03 12:57:55.381  - debug: fb-checkpresence.0 (3599) loopDevices starts
2020-12-03 12:57:55.382  - debug: fb-checkpresence.0 (3599) loopDevices ends after 0,440342 s
2020-12-03 12:57:56.113  - info: host.buanet-iobroker instance system.adapter.alexa2.0 started with pid 27829
2020-12-03 12:57:58.330  - info: alexa2.0 (27829) starting. Version 3.3.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v12.19.1, js-controller: 3.1.6
2020-12-03 12:58:06.180  - info: alexa2.0 (27829) Alexa-Push-Connection established. Disable Polling
2020-12-03 12:58:10.363  - info: alexa2.0 (27829) Unknown Device, but enabling commands, Try it and report back if commands work.
2020-12-03 12:58:10.364  - info:  alexa2.0 (27829) Report to developer as GitHub issue with details for  device. Please grab full next line pot. from logfile on disk if cutted
2020-12-03 12:58:10.364  - info:  alexa2.0 (27829)     Device-type:A1ZB65LA390I4K  (MICROPHONE,DIALOG_INTERFACE_VERSION,VOLUME_SETTING,SUPPORTS_LOCALE_SWITCH,SUPPORTS_LOCALE,CUSTOM_ALARM_TONE,REMINDERS,SOUND_SETTINGS,ASX_TIME_ZONE,PERSISTENT_CONNECTION,SUPPORTS_SOFTWARE_VERSION,TIMERS_AND_ALARMS,ASCENDING_ALARM_VOLUME,NO_TIME_ZONE_SETTING)
2020-12-03 12:58:16.722  - error: alexa2.0 (27829) The "Echo-Devices.G090LV03732500F4.Music-Provider." is invalid. Ids are not allowed to end in "."
at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
at /opt/iobroker/node_modules/iobroker.alexa2/main.js:352:25
at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
at processImmediate (internal/timers.js:461:21)
2020-12-03 12:58:26.446  - error: alexa2.0 (27829) The "Echo-Devices.G090LF1072530TM2.Music-Provider." is invalid. Ids are not allowed to end in "."
at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
at /opt/iobroker/node_modules/iobroker.alexa2/main.js:352:25
at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
at processImmediate (internal/timers.js:461:21)

`

**Comment by beandi** [comment] 2020-12-03 12:44
Same here, "Speak" does not work anymore. Had no issues for the last ~18 months. (Adapter 3.3.1)
iobroker on Debian.

**Comment by canim60** [comment] 2020-12-03 18:57
habe mein Pi neugestartet, seit dem funktioniert der Speak nichtmehr, über Routine geht es einwandfrei

**Comment by Lodenhaarbaer** [comment] 2020-12-03 19:02
Hallo,

ich habe das gleiche Problem seit einem Neustart des Pi. Im Log steht das gleiche wie bei lordnaicon. Über eine Routine in der Alexa-App funktioniert alles.

**Comment by polocup100** [comment] 2020-12-03 22:30
nothing happens, when i start the routine from the adapter

best regards Sascha

Am Do., 3. Dez. 2020 um 08:30 Uhr schrieb Ingo Fischer <
notifications@github.com>:

**Comment by polocup100** [comment] 2020-12-03 22:34
2020-12-03 22:31:18.702  -  [32minfo [39m: alexa2.0 (25090) Proxy IP
not set, use first network interface (192.168.2.20) instead
2020-12-03 22:31:26.452  -  [32minfo [39m: alexa2.0 (25090)
Alexa-Push-Connection established. Disable Polling
2020-12-03 22:31:27.276  -  [32minfo [39m: alexa2.0 (25090) Unknown
Device, but enabling commands, Try it and report back if commands
work.
2020-12-03 22:31:27.277  -  [32minfo [39m: alexa2.0 (25090) Report to
developer as GitHub issue with details for device. Please grab full
next line pot. from logfile on disk if cutted
2020-12-03 22:31:27.278  -  [32minfo [39m: alexa2.0 (25090)
Device-type:A9YU3XB1OZ676
(CHANGE_NAME,REMINDERS,SLEEP,VOLUME_SETTING,TIMERS_AND_ALARMS,I_HEART_RADIO,TUNE_IN,DEREGISTER_DEVICE,MICROPHONE,AUDIBLE,MUSIC_SKILL,KINDLE_BOOKS,PERSISTENT_CONNECTION,AMAZON_MUSIC,GOLDFISH,DEEZER,APPLE_MUSIC,TIDAL,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,AUDIO_PLAYER,DREAM_TRAINING,SIRIUSXM)
2020-12-03 22:31:27.374  -  [32minfo [39m: alexa2.0 (25090) Unknown
Device, but enabling commands, Try it and report back if commands
work.
2020-12-03 22:31:27.375  -  [32minfo [39m: alexa2.0 (25090) Report to
developer as GitHub issue with details for device. Please grab full
next line pot. from logfile on disk if cutted
2020-12-03 22:31:27.376  -  [32minfo [39m: alexa2.0 (25090)
Device-type:A30YDR2MK8HMRV
(UPDATE_WIFI,LEMUR_ALPHA,EQUALIZER_CONTROLLER_BASS,GADGETS,DISPLAY_BRIGHTNESS_ADJUST,SALMON,TUPLE_CATEGORY_A,PAIR_REMOTE,MUSIC_SKILL,KINDLE_BOOKS,EFDCARDS,PERSISTENT_CONNECTION,AMAZON_MUSIC,GOLDFISH,TIDAL,VOICE_TRAINING,SIRIUSXM,CHANGE_NAME,SUPPORTS_SOFTWARE_VERSION,DIALOG_INTERFACE_VERSION,SET_LOCALE,ALEXA_GESTURES,DEREGISTER_DEVICE,EQUALIZER_CONTROLLER_MIDRANGE,PAIR_BT_SINK,ALEXA_PRESENCE,SUPPORT_CALENDAR_ALERT,EARCONS,AUDIO_PLAYER,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TUPLE,EQUALIZER_CONTROLLER_TREBLE,BT_PAIRING_FLOW_V2,SUPPORTS_LOCALE,MULTI_WAKEWORDS_SUPPORTED,REMINDERS,DS_VOLUME_SETTING,SUPPORTS_LOCALE_SWITCH,VOLUME_SETTING,TUNE_IN,TAHOE_BYOD,DISPLAY_ADAPTIVE_BRIGHTNESS,DISPLAY_POWER_TOGGLE,REQUIRES_OOBE_FOR_SETUP,GUARD_EARCON,FLASH_BRIEFING,POPTART,ACTIVE_AFTER_FRO,SLEEP,AUDIO_CONTROLS,PAIR_BT_SOURCE,CUSTOM_ALARM_TONE,ASCENDING_ALARM_VOLUME,TIMERS_AND_ALARMS,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,I_HEART_RADIO,CLOCK_FORMAT_24_HR,MICROPHONE,AUDIBLE,FAR_FIELD_WAKE_WORD,SET_TIME_ZONE,DEEZER,SOUND_SETTINGS,PANDORA,APPLE_MUSIC,DREAM_TRAINING)
2020-12-03 22:31:27.394  -  [32minfo [39m: alexa2.0 (25090) Unknown
Device, but enabling commands, Try it and report back if commands
work.
2020-12-03 22:31:27.395  -  [32minfo [39m: alexa2.0 (25090) Report to
developer as GitHub issue with details for device. Please grab full
next line pot. from logfile on disk if cutted
2020-12-03 22:31:27.395  -  [32minfo [39m: alexa2.0 (25090)
Device-type:A1ZB65LA390I4K
(SUPPORTS_LOCALE,REMINDERS,CUSTOM_ALARM_TONE,ASCENDING_ALARM_VOLUME,SUPPORTS_SOFTWARE_VERSION,SUPPORTS_LOCALE_SWITCH,VOLUME_SETTING,TIMERS_AND_ALARMS,DIALOG_INTERFACE_VERSION,ASX_TIME_ZONE,MICROPHONE,PERSISTENT_CONNECTION,SOUND_SETTINGS,NO_TIME_ZONE_SETTING)
2020-12-03 22:31:31.131  -  [31merror [39m: alexa2.0 (25090) The
"Echo-Devices.42f978136a6048428f755ebad25e46e0.Music-Provider." is
invalid. Ids are not allowed to end in "."
    at Adapter.setObject
(/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
    at /opt/iobroker/node_modules/iobroker.alexa2/main.js:346:25
    at Immediate._onImmediate
(/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
    at processImmediate (internal/timers.js:456:21)
2020-12-03 22:32:02.694  -  [31merror [39m: alexa2.0 (25090) The
"Echo-Devices.4b3d754355dc497d99186e0c0894ea5d.Music-Provider." is
invalid. Ids are not allowed to end in "."
    at Adapter.setObject
(/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
    at /opt/iobroker/node_modules/iobroker.alexa2/main.js:346:25
    at Immediate._onImmediate
(/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
    at processImmediate (internal/timers.js:456:21)
2020-12-03 22:35:56.549  -  [32minfo [39m: host.raspberrypi4-iobroker
stopInstance system.adapter.alexa2.0 (force=false, process=true)
2020-12-03 22:35:56.565  -  [32minfo [39m: host.raspberrypi4-iobroker
stopInstance system.adapter.alexa2.0 send kill signal
2020-12-03 22:35:56.584  -  [32minfo [39m: alexa2.0 (25090) Got
terminate signal TERMINATE_YOURSELF
2020-12-03 22:35:56.589  -  [32minfo [39m: alexa2.0 (25090) terminating
2020-12-03 22:35:56.591  -  [32minfo [39m: alexa2.0 (25090) Terminated
(ADAPTER_REQUESTED_TERMINATION): Without reason


Am Mi., 2. Dez. 2020 um 08:50 Uhr schrieb Ingo Fischer <
notifications@github.com>:

**Comment by Apollon77** [comment] 2020-12-03 23:02
The Music Provider issue is fixed in 3.3.5 ... Rest we need to see

**Comment by Apollon77** [comment] 2020-12-03 23:03
Command still work on my devices ...

**Closed** 2020-12-03 23:16 UTC
Labels: question

**Comment by zaunermax** [comment] 2020-12-03 23:18
I've also noticed, that the announce command does not work on my sonos alexa connected device, not sure if the issue is connected 🤔 - I will investigate

**Comment by Apollon77** [comment] 2020-12-03 23:19
honestly: sonos speak/announce was broken by amazon several ties in the past :-(

**Comment by zaunermax** [comment] 2020-12-03 23:23
oh, didn't know that - never mind then ^^

**Comment by zaunermax** [comment] 2020-12-03 23:30
If I wanted to dig into the bugfixing myself, could you point me to somwhere where I could get started with developing/fixing adapters? 🤔 I tried searching the forums but i found it a bit tedious - thanks in advance 🙌

**Comment by Apollon77** [comment] 2020-12-03 23:38
Starting this with alexa2 adapter would be a veeer complex topic ;-) Ok the fix for this Music provider issue was rather easy, right because it is just ignoring a new entry that do not have a name ;-)

For in general adapter development we have groups in Telegram and discord and also in the forum ... if you do not have an own idea you can check the Adapter requests if something might interest you ;-) Then we support all new devs the best we can in the above mentioned channels

**Comment by Apollon77** [comment] 2020-12-03 23:39
a good starting point is also https://www.iobroker.net/#de/documentation/dev/adapterdev.md

**Comment by ppb1308** [comment] 2020-12-04 07:32
Hallo Apollon77,

> The Music Provider issue is fixed in 3.3.5 ... Rest we need to see
Wann sehe ich 3.3.5 im latest repository?
Ich habe bisher nur 3.3.2 dort verfügbar...

**Comment by Apollon77** [comment] 2020-12-04 07:33
Lade mal dein Repo neu (Adapter der pfeil im kreis ... sonst Github install

**Comment by Lodenhaarbaer** [comment] 2020-12-04 07:40
Danke, 3.3.5 funktioniert!

**Comment by ppb1308** [comment] 2020-12-04 13:43
Ja, danke, konnte 3.5.5 installieren und geht nun wieder.

> Lade mal dein Repo neu (Adapter der pfeil im kreis ... sonst Github install
