### ISSUE TITLE
Set alexa alarm volume

### ISSUE THREAD

**Issue by manmac2** [Apollon77/ioBroker.alexa2#696] opened 2021-05-22 06:35 UTC
Dear All,

since a while I realised having a (for me ;)) serious problem with the alexa alarm volume. As I have a very quite environment also my alexa alarm is set to the lowest possible volume (5). But regularly I find alexa increasing the volume (~20) of the alarm on it's own. I have already created a blockly script to decrease the volume if I realise that it's to loud but that's only a work around as it doesn't prevent to start very loud.

In the Alexa app I check every evening whether the volume level has been increased again and I turn it back to the lowest level. It would be great if there is a possibility in the adapter to set (beside the actual volume) also the volume of the alarm.   

Although it seems to be a clear Alexa bug I hope there is a possibility to solve it via this adapter and I would be very glad if someone could give a hint if it is already possible to solve that problem in another way.

Thanks
Best manmac

**Comment by Apollon77** [comment] 2021-05-22 08:16
Can you set "alarm level" (What is that exactly?) In the Alexa App? WHere?

**Comment by manmac2** [comment] 2021-05-22 08:39
![000FCCCA-004D-4B7F-BF45-07C10A4DEDD4](https://user-images.githubusercontent.com/56073319/119220193-a139d400-bae9-11eb-95fd-ae5d70518b11.png)

This dialogue can be acessed in the Alexa app (ios) via more / alarms & timers / settings (at the bottom of the page) / <choose device> 

Best
manmac

**Comment by Apollon77** [comment] 2021-05-22 15:32
Then it is duplicate of #87

**Closed by Apollon77** 2021-05-22 15:32 UTC
Labels: question

**Comment by manmac2** [comment] 2021-05-22 18:05
Oh, thanks for the feedback. 
While I just need to set the volume in general setting it for individual alarms would probably enable even more use cases :)
Best manmac
